exec: [ "/sbin/my_init" ]
data_sources: [ defaults, file, environment, environment_json ]
template_sources: [ file ]
default_environment: local

environments:
  production:
    global_values:
      dachi_environment: production
  development:
    global_values:
      dachi_environment: development
  local:
    global_values:
      dachi_environment: local

defaults:
  global:
    hostname: localhost
  dachi_environment.erb:
    target: /var/www/dachi_environment
  nginx-config.erb:
    target: /etc/nginx/sites-available/default
  tail.sh.erb:
    target: /etc/service/tail/run
    perms: 0755
  nginx.sh.erb:
    target: /etc/service/nginx/run
    perms: 0755
  phpfpm.sh.erb:
    target: /etc/service/phpfpm/run
    perms: 0755
